name: Update Mullvad Data

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 1 hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download latest lists
        run: wget ${{ secrets.MULLVAD }} -O mullvad.sh && bash mullvad.sh
      
      - name: Force add and commit
        run: |
          git config --local user.email "scriptzteam@gmail.com"
          git config --local user.name "scriptzteam"
          
          # Stage the updated Readme
          git add -f Readme.md
          
          # Check if Readme.md specifically has staged changes (M or A)
          if git status --porcelain | grep -q '^[MA]  Readme.md'; then
            echo "Changes detected in Readme.md, committing..."
            git commit -m "Update Mullvad Data [skip ci]"
            git push
          else
            echo "No changes to Readme.md to commit"
          fi
